name: pytest for examples

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    strategy:
      matrix:
        python-version: [3.8.5]
        os: ["ubuntu-22.04"]

    runs-on: "${{ matrix.os }}"

    name: pytest for examples
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup conda
      uses: s-weigand/setup-conda@v1 
      with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: anaconda
    - run: conda --version
    - run: which python

    - name: Install dependencies and Project
      run: |
         conda config --add channels conda-forge
         conda config --set channel_priority strict
         conda install -c conda-forge --file requirements.txt
         conda install scipy
         conda install pip
         
        
         pip install .
         pip install ase==3.22.1
         echo "${GITHUB_WORKSPACE}/bin" >> $GITHUB_PATH
         #pip install sgdml 

    - name: Install Gfortran and Compile Driver
      shell: bash
      run: |
         sudo apt-get update
         sudo apt-get install gfortran
         cd drivers/f90
         make

    - name: pytests for examples
      shell: bash
      run: |
         i-pi-tests -t examples
