name: Python application

on:
  push:
  pull_request:
    branches: [ master-py3 ]

jobs:
  build:

    strategy:
      matrix:
        python-version: [3.7]
        #os: ["ubuntu-latest", "macos-latest"]
        os: ["ubuntu-latest"]

    runs-on: "${{ matrix.os }}"

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install .
        echo "::add-path::${GITHUB_WORKSPACE}/bin"


    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --config=setup.cfg --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --config=setup.cfg --count  --statistics

    - name: Install GFortran Linux
      if: contains(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update
        sudo apt-get install gfortran

#    - name: Install GFortran macOS
#      if: contains(matrix.os, 'macos')
#      run: brew install gcc || brew upgrade gcc || true


    - name: Compile Driver
      shell: bash
      run: |
         cd drivers
         make

    - name: Pytest
      shell: bash
      run: |
        pwd
        pytest 
        #pytest --cov=./ --cov-report=xml

    #- name: Upload coverage
    #  uses: codecov/codecov-action@v1
    #  with:
    #    token: ${{ secrets.CODECOV_TOKEN }}
    #    file: ./coverage.xml
    #    flags: tests
    #    name: codecov-umbrella
    #    fail_ci_if_error: true
